### ISSUE TITLE
Segfault (signal 11) on q2proded

### ISSUE THREAD

**Issue by jocarren** [packetflinger/openra2#1]
Hi, 
I'm very glad to find source code for RA2, thank you very very much. 

I built from your source on x64 (gamex86_64.so), but when I try to run it on q2proded it segfaults. I had the same issue with the original RA2 and r1q2ded, then used r1q2ded-old and works fine. 

¿Any idea why this happens?

**Comment by joe0x04** [comment]
Hey!
I was also looking for the source for RA2, but was unable to find it. So this project is a rewrite, and it's VERY early stage. I'm hoping to get it stable in the next couple of weeks though. 

I always found RA2 confusing as far as the teams in the menus...so hopefully this will make things much more simple.

Stay tuned

**Comment by jocarren** [comment]
```
So, I ran a debugger (gdb) on gamex86_64.so compiled from your source. I got this:

Leyendo símbolos desde openra2/gamex86_64.so...hecho.
(gdb) run
Starting program: /home/jocarren/.quake2/openra2/gamex86_64.so

Program received signal SIGSEGV, Segmentation fault.
SelectPrevItem (ent=0x0, itflags=0) at g_cmds.c:65
65          cl = ent->client;
(gdb) backtrace
#0  SelectPrevItem (ent=0x0, itflags=0) at g_cmds.c:65
(gdb)
```

The vecinity of line 65 of g_cmds.c is:

```
static void SelectPrevItem(edict_t *ent, int itflags)
{
    gclient_t   *cl;
    int         i, index;
    const gitem_t       *it;

    cl = ent->client;

    if (cl->layout == LAYOUT_MENU) {
        PMenu_Prev(ent);
        return;
    }
    if (cl->chase_target) {
        ChasePrev(ent);
        cl->chase_mode = CHASE_NONE;
        return;
}

```

Seems to me, there is no memory reserved for "cl", so it tries to access a segment that does not belong to it.

**Comment by joe0x04** [comment]
I haven't run into this crash using q2proded, but I've changed a bunch of stuff since then, maybe it's been taken care of.
