### ISSUE TITLE
[question] Linux compilation on x86_64

### ISSUE THREAD

**Issue by miquecg** [packetflinger/openra2#23]
Hi,

Nice work. I was trying to find a way to play RA2 on Linux 64 bits but it turns out that none of the binaries I've found is compatible. While I could compile Yamagi client for 32 bits architecture or even play the Windows game under Steam on Linux, I think your project could it make it work.

Have you ever tried to compile it for Linux? Does it work?

**Comment by joe0x04** [comment]
Hey,
Still very much a work in progress, but thanks! Yes it builds and works fine in Linux. It was actually developed on Linux. So just a simple clone and run `make` should build you a 64 bit linux shared library. I think the only non-standard dependency is `glib-2.0`.

**Comment by miquecg** [comment]
Cool, I will give it a try :+1: 

I have downloaded the original RA2 from [tastyspleen.net](http://tastyspleen.net/quake/downloads/mods/ra2/). Don't know if it's the most up to date version but anyway, I only need pak files, maps and so on, and the clients don't even need the shared library, right?

One last thing, is it possible to play with bots? I've found [this mod](https://planetquake.gamespy.com/Viewf216.html?view=Quake2.Detail&id=577) of the famous Eraser bot for RA2 but never tried.

**Comment by miquecg** [comment]
Project compiles without problems but for some reason the mod is not loaded. I can enter the game but it looks like a regular deathmatch. Pressing inventory doesn't bring the arena menu.

This is the same that happened to me with the original binaries. Probably something misconfigured on my side. Where can I start debugging it? Yamagi doesn't show errors btw.
