### ISSUE TITLE
Make end-of-match more...

### ISSUE THREAD

**Issue by joe0x04** [packetflinger/openra2#9]
It needs a different layout or soundbyte or something to show the match is over.

**Comment by joe0x04** [comment]
Each match gets an intermission at the end. Still need more sound bytes though.

**Comment by scollonp** [comment]
Right now, maps/matches actually do not progress and seem to be stuck in a loop. This has been confirmed by multiple testers.

**Comment by joe0x04** [comment]
looking into this...

**Comment by joe0x04** [comment]
matches progress, and I added a horn blast to the match intermission, good enough. c873680389bce8a4c18ecb69295006feca6c0022
